version: '3.8'


volumes:
  database:
    driver: 'local'

services:
  webapp:
    image: 'nginx:alpine'
    working_dir: /var/www/site
    volumes:
      - '.:/var/www/app:cached'
      - './docker/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf'
    ports:
      - '80:80'
    depends_on:
      - app
      - database
  app:
    build:
      context: .
      dockerfile: docker/dev/php/Dockerfile
      args:
        PUID: ${PUID}
        PGID: ${PGID}
    depends_on:
      - database
    volumes:
      - .:/var/www/app:cached

  database:
    image: 'postgres:11-alpine'
    volumes:
      - 'database:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15672:15672"